// <auto-generated />
namespace FlightJobs.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class aircraft_thumbnail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aircraft_thumbnail));
        
        string IMigrationMetadata.Id
        {
            get { return "202306122251183_aircraft_thumbnail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
